# Generated by Django 3.0.4 on 2020-07-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0002_auto_20200630_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
