# Generated by Django 3.0.4 on 2020-07-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0003_auto_20200701_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='commented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb.MyProfile'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='msg',
            field=models.TextField(null=True),
        ),
    ]
